In [5]:
import numpy as np

In [7]:
# 从一个Python列表创建
my_list = [1,2,3,4,5]
arr1 = np.array(my_list)

print("原始列表：",my_list)
print("创建的NumPy数组",arr1)
print("数组的类型：",type(arr1))
print("数组的维度（ndim）：",arr1.ndim)
print("数组的形状（shape）：",arr1.shape)
print("数组的数据类型（dtype）：",arr1.dtype)

原始列表： [1, 2, 3, 4, 5]
创建的NumPy数组 [1 2 3 4 5]
数组的类型： <class 'numpy.ndarray'>
数组的维度（ndim）： 1
数组的形状（shape）： (5,)
数组的数据类型（dtype）： int64


In [8]:
# 从一个嵌套列表创建
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2 = np.array(my_matrix)

print("创建的二维数组:\n", arr2) # \n 用于换行
print("数组的维度 (ndim):", arr2.ndim)
print("数组的形状 (shape):", arr2.shape) # 输出 (3, 3)，表示3行3列

创建的二维数组:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
数组的维度 (ndim): 2
数组的形状 (shape): (3, 3)


In [9]:
# 创建一个整数数组，但强制转换为浮点数类型
arr_int_to_float = np.array([1,2,3],dtype=float)
print("强制指定为浮点数的数组：",arr_int_to_float)
print("数组的数据类型（dtype）：",arr_int_to_float.dtype)

# 创建一个字符串数组
arr_str = np.array(['apple', 'banana', 'cherry'])
print("\n字符串数组:", arr_str)
print("数组的数据类型 (dtype):", arr_str.dtype)

强制指定为浮点数的数组： [1. 2. 3.]
数组的数据类型（dtype）： float64

字符串数组: ['apple' 'banana' 'cherry']
数组的数据类型 (dtype): <U6


In [14]:
#创建一个2行3列的全0数组
zeros_arr = np.zeros((2,3))

print("2行3列的全0数组\n",zeros_arr)
print("数组的数据类型",zeros_arr.dtype)

#也可以制定数据类型为整数
zeros_int_arr = np.zeros((2,3),dtype=int)
print("\n指定为整数的全0数组：\n",zeros_int_arr)
print("数组的数据类型",zeros_int_arr.dtype)

2行3列的全0数组
 [[0. 0. 0.]
 [0. 0. 0.]]
数组的数据类型 float64

指定为整数的全0数组：
 [[0 0 0]
 [0 0 0]]
数组的数据类型 int64


In [18]:
#创建一个3行1列的全1数组
ones_arr = np.ones((3,1))

print("3行1列的全1数组\n",ones_arr)
print("数组的数据类型",ones_arr.dtype)

3行1列的全1数组
 [[1.]
 [1.]
 [1.]]
数组的数据类型 float64


In [21]:
# 创建一个2行2列，所有元素都为7的数组
full_arr = np.full((2,2),7)
print(full_arr)
# 也可以填充浮点数或字符串
full_float_arr = np.full((2, 2), 3.14)
print("\n填充浮点数3.14的数组:\n", full_float_arr)

[[7 7]
 [7 7]]

填充浮点数3.14的数组:
 [[3.14 3.14]
 [3.14 3.14]]


In [23]:
# 从0到9 (不包含10)
arr_range1 = np.arange(10)
print("从0到9:", arr_range1)

# 从5到14 (不包含15)
arr_range2 = np.arange(5, 15)
print("从5到14:", arr_range2)

# 从0到10，步长为2
arr_range3 = np.arange(0, 11, 2)
print("从0到10，步长为2:", arr_range3)

# 也可以用于浮点数
arr_range4 = np.arange(0, 1, 0.2)
print("浮点数序列:", arr_range4)

arr_range5 = np.arange(35,43,0.8)
print("浮点数序列2：",arr_range5)

从0到9: [0 1 2 3 4 5 6 7 8 9]
从5到14: [ 5  6  7  8  9 10 11 12 13 14]
从0到10，步长为2: [ 0  2  4  6  8 10]
浮点数序列: [0.  0.2 0.4 0.6 0.8]
浮点数序列2： [35.  35.8 36.6 37.4 38.2 39.  39.8 40.6 41.4 42.2]


In [26]:
# 在0到10之间（包含0和10），均匀生成5个数字
lin_arr = np.linspace(0,10,5)
print(lin_arr)

[ 0.   2.5  5.   7.5 10. ]


In [27]:
# 创建一个2行3列的随机浮点数数组
rand_arr = np.random.rand(2,3)

print("2行3列的随机浮点数数组 (0到1之间):\n", rand_arr)

2行3列的随机浮点数数组 (0到1之间):
 [[0.87326332 0.50693685 0.55025486]
 [0.05491944 0.27387067 0.61290731]]


In [28]:
# 创建一个3行2列的标准正态分布随机数组(均值为0，标准差为1)
randn_arr = np.random.randn(3, 2)

print("3行2列的标准正态分布随机数组:\n", randn_arr)

3行2列的标准正态分布随机数组:
 [[ 1.58248353 -0.06935137]
 [ 1.48214587 -0.14623785]
 [-0.13981883  1.10414233]]


In [34]:
randint_arr1 = np.random.randint(0,10,size=5)
print(randint_arr1)
randint_arr2 = np.random.randint(1,100,(2,2))
print(randint_arr2)

[8 7 9 7 9]
[[ 5 70]
 [11 95]]


In [48]:
my_ones = np.ones((3,4))
print(my_ones,"\nShape:",my_ones.shape,"\nDtype:",my_ones.dtype,"\n")

my_sequence = np.arange(10,31,2)
print(my_sequence,"\nShape:",my_sequence.shape,"\nDtype:",my_sequence.dtype,"\n")

my_random = np.random.randint(1,51,size=(2,3))
print(my_random,"\nShape:",my_random.shape,"\nDtype:",my_random.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
Shape: (3, 4) 
Dtype: float64 

[10 12 14 16 18 20 22 24 26 28 30] 
Shape: (11,) 
Dtype: int64 

[[30 40 35]
 [10 14 27]] 
Shape: (2, 3) 
Dtype: int32


In [3]:
import os
print(os.getcwd())

C:\Users\77386\代码
