In [1]:
import numpy as np

# 没有广播：需要手动复制向量
A = np.array([[1,2,3],[4,5,6]])  # 2×3矩阵
B = np.array([10,20,30])         # 1×3向量
B_repeat = np.tile(B, (2,1))     # 手动复制B成2×3（每行都和B一样）
print("手动复制后相加：\n", A + B_repeat)  # 输出 [[11,22,33],[14,25,26]]

# 有广播：自动扩展，代码更简洁
print("广播自动扩展后相加：\n", A + B)  # 输出和上面完全一样，无需手动复制

手动复制后相加：
 [[11 22 33]
 [14 25 36]]
广播自动扩展后相加：
 [[11 22 33]
 [14 25 36]]


In [2]:
# 标量 + 1维数组
arr1d = np.array([1,2,3])
print("标量+1维数组：", arr1d + 2)  # 输出 [3,4,5]（每个元素加2）

# 标量 × 2维数组
arr2d = np.array([[1,2],[3,4]])
print("标量×2维数组：\n", arr2d * 3)  # 输出 [[3,6],[9,12]]（每个元素乘3）

标量+1维数组： [3 4 5]
标量×2维数组：
 [[ 3  6]
 [ 9 12]]


In [3]:
# 场景2.1：1维数组（行向量）和2维数组（按行扩展）
A = np.array([[1,2,3],[4,5,6],[7,8,9]])  # 3×3矩阵
B = np.array([10,20,30])                  # 1×3行向量（补全后(1,3)）
print("行向量+矩阵（按行扩展）：\n", A + B)
# 输出：
# [[11,22,33]
#  [14,25,36]
#  [17,28,39]]  # B的每一行都和A的对应行相加

# 场景2.2：1维数组（列向量）和2维数组（按列扩展）
C = np.array([[100],[200],[300]])         # 3×1列向量（补全后(3,1)）
print("列向量+矩阵（按列扩展）：\n", A + C) # C的每一列都和A的对应列相加

行向量+矩阵（按行扩展）：
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
列向量+矩阵（按列扩展）：
 [[101 102 103]
 [204 205 206]
 [307 308 309]]


In [5]:
import numpy as np

x = np.array([1,2,3])        # 形状(3,) → 补全后(1,3)
y = np.array([4,5]).reshape(2,1)  # 手动改为(2,1) → 补全后(2,1)（无需补维度）

# 现在检查兼容性：
# x补全后(1,3)，y形状(2,1)
# 第一维：1和2（有一个是1，兼容）
# 第二维：3和1（有一个是1，兼容）
grid = x + y
print("两个数组广播成2×3：\n", grid)
# 输出：
# [[5 6 7]
#  [6 7 8]]  # 正确运行，无报错

两个数组广播成2×3：
 [[5 6 7]
 [6 7 8]]


In [8]:
x = np.array([1,2,3])  # (3,)
y = np.array([4,5])    # (2,)

# 应用：生成二维坐标网格（机器学习中常用）
xx, yy = np.meshgrid(x, y)
print("\n网格x坐标：\n", xx)  # 输出 [[1,2,3],[1,2,3]]
print("网格y坐标：\n", yy)  # 输出 [[4,4,4],[5,5,5]


网格x坐标：
 [[1 2 3]
 [1 2 3]]
网格y坐标：
 [[4 4 4]
 [5 5 5]]
