In [2]:
import numpy as np
arr = np.array([1,2,3])
print(type(arr),"\n",arr.ndim,"\n",arr.shape,"\n",arr.dtype)

<class 'numpy.ndarray'> 
 1 
 (3,) 
 int64


In [33]:
arr = np.arange(6) # 原数组：[0 1 2 3 4 5]，shape=(6,)
# 1. 改为2行3列的二维数组
arr1 = arr.reshape(2, 3) 
print(arr1.shape) # 输出(2,3)
# 2. 改为3行2列的二维数组
arr2 = arr.reshape(3, 2)
print(arr2.shape) # 输出(3,2)
# 3. 用-1自动计算某一维度（常用！）
arr3 = arr.reshape(-1, 2) # 固定列数为2，行数自动算（6/2=3）
print(arr3.shape) # 输出(3,2)
arr1[0,1] = 9
print(arr) #与原数组关联
print(arr1)

(2, 3)
(3, 2)
(3, 2)
[0 9 2 3 4 5]
[[0 9 2]
 [3 4 5]]


In [14]:
arr = np.arange(6)
arr.resize(2,3)
print(arr,"\nShape:",arr.shape)

[[0 1 2]
 [3 4 5]] 
Shape: (2, 3)


In [17]:
arr = np.array([[1,2,3],[4,5,6]]) # shape=(2,3)
arr_t = arr.T # 转置
print(arr_t.shape) # 输出（3,2）
print(arr,"\n\n",arr_t)

(3, 2)
[[1 2 3]
 [4 5 6]] 

 [[1 4]
 [2 5]
 [3 6]]


In [34]:
arr = np.array([[1,2],[3,4]])
arr_ravel = arr.ravel()
arr_ravel[0] = 100 # 修改展平数组
print(arr) # 原数组也变：[[100,2],[3,4]]

arr_flatten = arr.flatten()
print(arr_flatten)
arr_flatten[1] = 200
print(arr) #与原数组不关联
print(arr_flatten)
arr_reshape = arr.reshape(-1)
print(arr_reshape) # 输出[100 2 3 4]

[[100   2]
 [  3   4]]
[100   2   3   4]
[[100   2]
 [  3   4]]
[100 200   3   4]
[100   2   3   4]


In [41]:
arr1 = np.array([[1,2],[3,4]]) # shape=(2,2)
arr2 = np.array([[5,6],[7,8]]) # shape=(2,2)（列数与arr1一致）
arr_v = np.vstack((arr1, arr2)) # 注意传参是元组
print(arr_v.shape) # 输出(4,2)（行数2+2=4，列数不变）
arr_h = np.hstack((arr1,arr2))
print(arr_h)
arr_h[0,0] = 100
print(arr1) #与原数组不关联
print(arr_h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]]
[[100   2   5   6]
 [  3   4   7   8]]


In [46]:
arr_concat_v = np.concatenate((arr1,arr2),axis=0) # 垂直堆叠（axis=0）
print(arr_concat_v)
arr_concat_h = np.concatenate((arr1,arr2),axis=1) # 水平堆叠（axis=1）
print(arr_concat_h)
arr_concat_h[0,0] = 100
print(arr1) #与原数组不关联
print(arr_concat_h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]]
[[100   2   5   6]
 [  3   4   7   8]]


In [91]:
# 垂直拆分vsplit
arr = np.arange(12).reshape(6, 2) # shape=(6,2)（6行2列）
# 拆成3个小数组（6行 ÷ 3 = 2行/数组）
arr_vs = np.vsplit(arr, 3)
print(len(arr_vs)) # 输出3（拆成3个）
print(arr_vs[0].shape) # 输出(2,2)（每个小数组2行2列）
# 水平拆分hsplit
arr = np.arange(12).reshape(2, 6) # shape=(2,6)（2行6列）
# 拆成2个小数组（6列 ÷ 2 = 3列/数组）
arr_hs = np.hsplit(arr, 2)
print(arr_hs[0]) # 输出(2,3)（每个小数组2行3列）
arr = np.linspace(2,72,36).reshape(6,6)
print(arr)
arr_split_v = np.split(arr,3,axis=0)
arr_split_v[0][0,0] = 100 #与原数组关联
print(arr)
print(arr_split_v)
arr_split_h = np.split(arr,2,axis=1)
print(type(arr),type(arr_split_h)) #注意！！！类型不同

3
(2, 2)
[[0 1 2]
 [6 7 8]]
[[ 2.  4.  6.  8. 10. 12.]
 [14. 16. 18. 20. 22. 24.]
 [26. 28. 30. 32. 34. 36.]
 [38. 40. 42. 44. 46. 48.]
 [50. 52. 54. 56. 58. 60.]
 [62. 64. 66. 68. 70. 72.]]
[[100.   4.   6.   8.  10.  12.]
 [ 14.  16.  18.  20.  22.  24.]
 [ 26.  28.  30.  32.  34.  36.]
 [ 38.  40.  42.  44.  46.  48.]
 [ 50.  52.  54.  56.  58.  60.]
 [ 62.  64.  66.  68.  70.  72.]]
[array([[100.,   4.,   6.,   8.,  10.,  12.],
       [ 14.,  16.,  18.,  20.,  22.,  24.]]), array([[26., 28., 30., 32., 34., 36.],
       [38., 40., 42., 44., 46., 48.]]), array([[50., 52., 54., 56., 58., 60.],
       [62., 64., 66., 68., 70., 72.]])]
<class 'numpy.ndarray'> <class 'list'>


In [102]:
arr = np.arange(1,10)
print(arr,"\nShape:",arr.shape) #拆分时要用axis=0
arr1 = np.split(arr,3,axis=0)
print(arr1)
arr = np.arange(1,28)
arr_reshape = arr.reshape(3,1,9)
print(arr_reshape)
print(arr_reshape.shape)
arr_t = arr_reshape.T
print(arr_t)
print(arr_t.shape)

[1 2 3 4 5 6 7 8 9] 
Shape: (9,)
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[[[ 1  2  3  4  5  6  7  8  9]]

 [[10 11 12 13 14 15 16 17 18]]

 [[19 20 21 22 23 24 25 26 27]]]
(3, 1, 9)
[[[ 1 10 19]]

 [[ 2 11 20]]

 [[ 3 12 21]]

 [[ 4 13 22]]

 [[ 5 14 23]]

 [[ 6 15 24]]

 [[ 7 16 25]]

 [[ 8 17 26]]

 [[ 9 18 27]]]
(9, 1, 3)


In [9]:
# ① 用np.newaxis增加维度（1维→2维列向量）
arr1d = np.array([1,2,3])
arr2d_col = arr1d[:, np.newaxis]  # 列向量：shape从(3,)→(3,1)
arr2d_row = arr1d[np.newaxis, :]  # 行向量：shape从(3,)→(1,3)
print("1维→2维列向量（shape）：", arr2d_col.shape)  # 输出 (3,1)
print("1维→2维行向量（shape）：", arr2d_row.shape)  # 输出 (1,3)

# ② 用squeeze()删除长度为1的维度
arr_with_1dim = np.array([[[1,2]], [[3,4]]])  # shape=(2,1,2)
print(arr_with_1dim) #有一个多余维度导致出现空行
arr_squeezed = arr_with_1dim.squeeze()  # 删除中间的1维，shape→(2,2)
print("\n删除冗余维度后的shape：", arr_squeezed.shape)  # 输出 (2,2)

1维→2维列向量（shape）： (3, 1)
1维→2维行向量（shape）： (1, 3)
[[[1 2]]

 [[3 4]]]

删除冗余维度后的shape： (2, 2)


In [10]:
# 正例1：(2,3) 和 (3,) → 可广播
A = np.array([[1,2,3],[4,5,6]])  # shape=(2,3)
B = np.array([10,20,30])          # shape=(3,)→补成(1,3)
C = A + B  # B被扩展为[[10,20,30],[10,20,30]]，再和A相加
print("正例1（可广播）结果：\n", C)

# 正例2：(3,1) 和 (1,3) → 可广播
D = np.array([[1],[2],[3]])  # shape=(3,1)
E = np.array([[10,20,30]])   # shape=(1,3)
F = D * E  # D扩展为(3,3)，E扩展为(3,3)，对应元素相乘
print("\n正例2（可广播）结果：\n", F)

# 反例：(2,3) 和 (2,) → 不可广播（最后一维3≠2）
G = np.array([[1,2,3],[4,5,6]])  # shape=(2,3)
H = np.array([10,20])            # shape=(2,)→补成(1,2)，最后一维1≠3
# print(G + H)  # 运行会报错

正例1（可广播）结果：
 [[11 22 33]
 [14 25 36]]

正例2（可广播）结果：
 [[10 20 30]
 [20 40 60]
 [30 60 90]]


In [11]:
# ① 浅拷贝（view()）
original = np.array([[1,2],[3,4]])
shallow_copy = original.view()  # 浅拷贝

# 修改浅拷贝的元素，原数组会变
shallow_copy[0,0] = 100
print("浅拷贝修改后，原数组：\n", original)  # 原数组[0,0]变成100

# ② 深拷贝（copy()）
original2 = np.array([[1,2],[3,4]])
deep_copy = original2.copy()  # 深拷贝

# 修改深拷贝的元素，原数组不变
deep_copy[0,0] = 200
print("\n深拷贝修改后，原数组：\n", original2)  # 原数组[0,0]还是1

浅拷贝修改后，原数组：
 [[100   2]
 [  3   4]]

深拷贝修改后，原数组：
 [[1 2]
 [3 4]]
