In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_eye = np.eye(4) # 对角矩阵，从左上向右下一条线是1，其余为0
arr_zeros = np.zeros((2,3))
arr_rand = np.random.randint(1,10,(2,3))
print(arr,'\n',arr_eye,'\n',arr_zeros,'\n',arr_rand)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
 [[0. 0. 0.]
 [0. 0. 0.]] 
 [[3 7 6]
 [1 5 6]]


In [11]:
A = np.array([[1,2],[3,4]])  # 2x2数组
B = np.array([[5,6],[7,8]])  # 2x2数组

# 1. 元素级乘法（*）：对应位置相乘
print(A * B)

# 2. 矩阵乘法（@ 或 np.dot()）：按矩阵规则计算
print(A @ B)  # 等价于 np.dot(A, B)
# 输出：[[1*5+2*7, 1*6+2*8], 
#        [3*5+4*7, 3*6+4*8]]

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [24]:
'''
即时练习 1：创建矩阵并区分乘法
创建一个 2 行 3 列的矩阵C（元素为 [1,2,3],[4,5,6]）和 3 行 2 列的矩阵D（元素为 [7,8],[9,10],[11,12]）。
尝试计算C * D和C @ D，观察结果差异（思考：为什么C * D会报错？）。
'''
C = np.array([[1,2,3],[4,5,6]])
D = np.array([[7,8],[9,10],[11,12]])
print(C @ D)
D = D.reshape(2,3) # C、D行列数不同不能使用数组乘法
print(C * D)

[[ 58  64]
 [139 154]]
[[ 7 16 27]
 [40 55 72]]


In [29]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A + B)  # 矩阵加法
print(A - 2.5)  # 矩阵减标量

[[ 6  8]
 [10 12]]
[[-1.5 -0.5]
 [ 0.5  1.5]]


In [34]:
'''
即时练习 2：矩阵加减运算
已知E = np.array([[2,4],[6,8]])，F = np.array([[1,3],[5,7]])，计算E - F。
计算E + 3和F * 2（思考：F * 2是矩阵运算还是元素运算？）
'''
E = np.array([[2,4],[6,8]])
F = np.array([[1,3],[5,7]])
print(E - F,"\n",E + 3,"\n",F * 2) #后两者属于元素运算，符合广播机制

[[1 1]
 [1 1]] 
 [[ 5  7]
 [ 9 11]] 
 [[ 2  6]
 [10 14]]


In [36]:
# 1. 矩阵乘法（满足“前列=后行”：A(2x3) * B(3x2) → 结果(2x2)）
A = np.array([[1,2,3],[4,5,6]])  # 2x3
B = np.array([[7,8],[9,10],[11,12]])  # 3x2
print(A @ B)
# 输出：[[1*7+2*9+3*11, 1*8+2*10+3*12], 
#        [4*7+5*9+6*11, 4*8+5*10+6*12]]

# 2. 向量点积（两个1维数组）
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
print(np.dot(vec1, vec2))  # 1*4 + 2*5 + 3*6 = 32

[[ 58  64]
 [139 154]]
32


In [38]:
'''
即时练习 3：矩阵乘法与点积
已知G = np.array([[1,0],[0,1]])（2 阶单位矩阵），H = np.array([[3,4],[5,6]])，计算G @ H和H @ G（观察结果，思考单位矩阵的作用）。
计算向量vec3 = [2,4,6]和vec4 = [3,5,7]的点积
'''
G = np.array([[1,0],[0,1]])
H = np.array([[3,4],[5,6]])
print(np.dot(G,H),"\n",np.dot(H,G)) #任何矩阵与单位矩阵相乘均等于它本身
print(np.dot([2,4,6],[3,5,7]))

[[3 4]
 [5 6]] 
 [[3 4]
 [5 6]]
68


In [48]:
A = np.array([[1,2],[3,4]])  # 2阶方阵
# 1. 转置
print(A.T)

# 2. 行列式（判断是否可逆）
det_A = np.linalg.det(A)
print(int(det_A))  # 结果≠0，可逆

# 3. 逆矩阵
inv_A = np.linalg.inv(A)
print(inv_A)

# 验证逆矩阵：A @ inv_A 应接近单位矩阵（浮点数误差）
print(A @ inv_A)

[[1 3]
 [2 4]]
-2
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [43]:
I = np.array([[2,5],[1,3]])
print(np.linalg.det(I)) #可逆
I_inv = np.linalg.inv(I)
print(I_inv)
print(I @ I_inv)
print(I_inv @ I) #结果一样

1.0
[[ 3. -5.]
 [-1.  2.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [50]:
'''
模块 4：特征值与特征向量（机器学习常用）
对 n 阶方阵 A，若存在标量 λ（特征值）和非零向量 v（特征向量），满足A @ v = λ * v，可通过np.linalg.eig()计算。
'''
A = np.array([[1,2],[3,4]])
eigenvalues,eigenvectors = np.linalg.eig(A)
print("特征值：", eigenvalues)  # 输出两个特征值
print("特征向量（列向量）：\n", eigenvectors)

# 验证：A@v ≈ λ*v（取第一个特征值和特征向量）
v1 = eigenvectors[:,1]  # 第二列是第二个特征向量
lambda1 = eigenvalues[1]
print("A@v1：", A @ v1)
print("λ1*v1：", lambda1 * v1)
# 输出应近似相等（浮点数误差）

特征值： [-0.37228132  5.37228132]
特征向量（列向量）：
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
A@v1： [-2.23472698 -4.88542751]
λ1*v1： [-2.23472698 -4.88542751]


In [59]:
'''
即时练习 5：特征值验证
已知方阵J = np.array([[3,1],[1,3]])，求其特征值和特征向量，并验证J@v = λ*v（任选一个特征值和向量）。
'''
J = np.array([[3,1],[1,3]])
J_λ,J_v = np.linalg.eig(J)
print(J_λ,"\n",J_v)
print(J @ J_v[:,0])
print(J_λ[0] * J_v[:,0])

[4. 2.] 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[2.82842712 2.82842712]
[2.82842712 2.82842712]


In [60]:
A = np.array([[1,2],[3,4],[5,6]])  # 3x2
vec = np.array([10,20])  # 1x2（向量）
print(A + vec)  # 广播：vec扩展为[[10,20],[10,20],[10,20]]

[[11 22]
 [13 24]
 [15 26]]


In [13]:
# 不可逆矩阵（行列式=0）
A = np.array([[1,2],[2,4]])  # 两行成比例，不可逆
pinv_A = np.linalg.pinv(A)
print(pinv_A)
# 验证：A@pinv_A@A ≈ A（伪逆的性质）
print(A @ pinv_A @ A)

[[0.04 0.08]
 [0.08 0.16]]
[[1. 2.]
 [2. 4.]]


In [38]:
from scipy.linalg import lu  # NumPy需借助scipy，或用np.linalg.svd
A = np.array([[2,1,-1],[4,-1,1],[-2,3,2]])
P, L, U = lu(A, permute_l=False)  # 单独返回置换矩阵P
print("置换矩阵P：\n",P)  # 记录行交换的信息
print("下三角矩阵L（未合并P）：\n",L)
print("上三角矩阵U：\n",U)
print("验证P@L@U：\n",P @ L @ U)
print("P@A:\n",P@A) 
print("验证P@A == L@U：\n", np.allclose(P@A,L@U))  # 输出True

置换矩阵P：
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
下三角矩阵L（未合并P）：
 [[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 0.5  0.6  1. ]]
上三角矩阵U：
 [[ 4.  -1.   1. ]
 [ 0.   2.5  2.5]
 [ 0.   0.  -3. ]]
验证P@L@U：
 [[ 2.  1. -1.]
 [ 4. -1.  1.]
 [-2.  3.  2.]]
P@A:
 [[-2.  3.  2.]
 [ 2.  1. -1.]
 [ 4. -1.  1.]]
验证P@A == L@U：
 False


In [37]:
L,U = lu(A,permute_l=True)  # 分解为L（下三角）和U（上三角）
print("下三角矩阵L：\n",L)
print("上三角矩阵U：\n",U)
print("验证L@U：\n",L @ U)  # 应等于原矩阵A
print("验证A == L@U：\n", np.allclose(A,L@U))  # 输出True

下三角矩阵L：
 [[ 0.5  0.6  1. ]
 [ 1.   0.   0. ]
 [-0.5  1.   0. ]]
上三角矩阵U：
 [[ 4.  -1.   1. ]
 [ 0.   2.5  2.5]
 [ 0.   0.  -3. ]]
验证L@U：
 [[ 2.  1. -1.]
 [ 4. -1.  1.]
 [-2.  3.  2.]]
验证A == L@U：
 True


In [5]:
import numpy as np

# 1. 定义系数矩阵A和常数项向量b
A = np.array([[2, 3],   # 2x2可逆方阵
              [4, -5]])
b = np.array([[8],      # 2x1常数项向量
              [-2]])

# 2. 验证A是否可逆（行列式≠0）
det_A = np.linalg.det(A)
print(f"A的行列式：{det_A:.2f}")  # 输出：-22.00（≠0，可逆）

# 3. 求A的逆矩阵
inv_A = np.linalg.inv(A)
print("A的逆矩阵inv_A：\n", inv_A)

# 4. 求解未知数x = inv_A @ b
x = inv_A @ b
print("方程组的解x：\n", x)  # 输出x₁, x₂

# 5. 验证解的正确性（代入原方程：A@x 应≈ b）
verify = A @ x
print("验证A@x：\n", verify)  # 输出[[8.], [-2.]]，与b完全一致

A的行列式：-22.00
A的逆矩阵inv_A：
 [[ 0.22727273  0.13636364]
 [ 0.18181818 -0.09090909]]
方程组的解x：
 [[1.54545455]
 [1.63636364]]
验证A@x：
 [[ 8.]
 [-2.]]
[8.] [-2.]


In [7]:
# 1. 定义超定方程组的A和b
A = np.array([[1, 2],   # 3x2非方阵（超定：3方程，2未知数）
              [3, 4],
              [5, 6]])
b = np.array([[3],      # 3x1常数项向量
              [7],
              [10]])

# 2. 尝试用逆矩阵求解（会报错！因为A非方阵，无法求逆）
try:
    inv_A = np.linalg.inv(A)
except np.linalg.LinAlgError as e:
    print("逆矩阵求解报错：", e)  # 输出报错：Last 2 dimensions of the array must be square

# 3. 用伪逆矩阵求解最小二乘解
pinv_A = np.linalg.pinv(A)  # 伪逆适用于任意矩阵
x = pinv_A @ b
print("伪逆求解的最小二乘解x：\n", x)  # 输出x₁≈0.5, x₂≈1.25

# 4. 验证解的误差（超定方程组无精确解，需看误差大小）
predict_b = A @ x  # 用解x计算“预测的b”
error = np.linalg.norm(predict_b - b)  # 计算误差（向量的2范数，即欧氏距离）
print("实际b：\n", b)
print("预测b（A@x）：\n", predict_b)
print("误差（||A@x - b||）：", error)  # 输出误差≈0.5（很小，说明解的精度高）

逆矩阵求解报错： Last 2 dimensions of the array must be square
伪逆求解的最小二乘解x：
 [[0.33333333]
 [1.41666667]]
实际b：
 [[ 3]
 [ 7]
 [10]]
预测b（A@x）：
 [[ 3.16666667]
 [ 6.66666667]
 [10.16666667]]
误差（||A@x - b||）： 0.408248290463863


In [9]:
import numpy as np
from scipy.linalg import lu_solve, lu_factor  # 用scipy的LU分解工具（更高效）

# 1. 定义可逆方程组（同场景1）
A = np.array([[2, 3],
              [4, -5]])
b = np.array([8, -2])  # 注意：lu_solve要求b是1维向量

# 2. LU分解：将A拆为L（下三角）和U（上三角），返回分解后的因子
lu_factor_A, piv = lu_factor(A)  # piv是置换矩阵索引，处理数值稳定性

# 3. 求解x：通过前向替换（解L@y = b）和后向替换（解U@x = y）
x = lu_solve((lu_factor_A, piv), b)
print("LU分解求解的x：", x)  # 输出[1. 2.]，与逆矩阵结果一致

# 4. 验证
print("验证A@x：", A @ x)  # 输出[ 8. -2.]，与b一致

LU分解求解的x： [1.54545455 1.63636364]
验证A@x： [ 8. -2.]


In [46]:
# ① 矩阵幂（2阶方阵的2次幂）
A = np.array([[1,2],[3,4]])
A_power2 = np.linalg.matrix_power(A, 2)  # A^2 = A@A
A_inv = np.linalg.matrix_power(A, -1)    # A^-1 = 逆矩阵（等价于np.linalg.inv(A)）
print("A的2次幂：\n", A_power2)
print("\nA的逆矩阵（A^-1）：\n", A_inv)

# ② 元素级函数（每个元素单独计算）
B = np.array([[1,2],[3,4]])
B_exp = np.exp(B)    # 每个元素求e的幂（e^1, e^2, ...）
B_log = np.log(B)    # 每个元素求自然对数（ln1, ln2, ...） 元素须大于0 支持复数
B_sin = np.sin(B)    # 每个元素求正弦值（sin1, sin2, ...） 支持复数
print("\n元素级指数运算：\n", np.round(B_exp, 2))  # 保留2位小数
print("\n元素级自然对数：\n", np.round(B_log, 2))
print("\n元素级三角函数：\n", np.round(B_sin, 2))

A的2次幂：
 [[ 7 10]
 [15 22]]

A的逆矩阵（A^-1）：
 [[-2.   1. ]
 [ 1.5 -0.5]]

元素级指数运算：
 [[ 2.72  7.39]
 [20.09 54.6 ]]

元素级自然对数：
 [[0.   0.69]
 [1.1  1.39]]

元素级三角函数：
 [[ 0.84  0.91]
 [ 0.14 -0.76]]


In [52]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

# 计算4种常用范数
norm_1 = np.linalg.norm(mat, ord=1)    # 1范数   各列元素绝对值之和中的最大值
norm_2 = np.linalg.norm(mat, ord=2)    # 2范数（默认）  最大奇异值（）
norm_inf = np.linalg.norm(mat, ord=np.inf)  # 无穷范数  各行元素绝对值之和中的最大值
norm_fro = np.linalg.norm(mat, ord="fro") # F范数   所有元素平方和开方
print("1范数（列范数）：", np.round(norm_1, 2))  # 输出 18.0（第三列15？不对，算错了：1+4+7=12，2+5+8=15，3+6+9=18 → 最大值18）
print("2范数（谱范数）：", np.round(norm_2, 2))  # 输出 16.84（计算结果）
print("无穷范数（行范数）：", np.round(norm_inf, 2))  # 输出 24.0（第三行7+8+9=24）
print("F范数：",np.round(norm_fro,2)) # 输出16.88
U,S,Vt = np.linalg.svd(mat) # S为奇异值数组
print("最大奇异值为：",max(S).round(2))

1范数（列范数）： 18.0
2范数（谱范数）： 16.85
无穷范数（行范数）： 24.0
F范数： 16.88
最大奇异值为： 16.85


In [54]:
# ① 可逆方阵（有唯一解）
A = np.array([[2,3],[4,5]])  # 2阶可逆方阵
b = np.array([8, 14])        # 常数项向量
x_exact = np.linalg.solve(A, b)  # 唯一解
print("方程组A@x=b的唯一解：", x_exact)
print("验证：A@x_exact =", A@x_exact)  # 输出 [8. 14.]，和b一致

# ② 超定方程组（方程数3>未知数2，无精确解）
A_over = np.array([[1,2],[3,4],[5,6]])  # 3行2列（3方程，2未知数）
b_over = np.array([3,7,10])             # 常数项向量
x_lstsq,residuals,_,_ = np.linalg.lstsq(A_over, b_over, rcond=None)
print("\n超定方程组的最小二乘解：", x_lstsq)
print("最小误差（残差）：", residuals[0])  # 误差越小，解越好

方程组A@x=b的唯一解： [1. 2.]
验证：A@x_exact = [ 8. 14.]

超定方程组的最小二乘解： [0.33333333 1.41666667]
最小误差（残差）： 0.1666666666666668


In [64]:
# 模拟数据：特征X（2个特征，5个样本），标签y（y = 2*X1 + 3*X2 + 0.1*噪声）
X = np.random.rand(5, 2)  # 5个样本，2个特征（X1, X2）
print("随机矩阵：\n",X)
Y = np.random.rand(5)
XTX_inv = np.linalg.inv(X.T@X)
beta = XTX_inv @ X.T @ Y
print("真实系数w1:",beta[0],"\n真实系数w2:",beta[1])
print("特征：\n",X)
# 用伪逆求回归系数w（w = pinv(X) @ Y）
X_pinv = np.linalg.pinv(X)
w = X_pinv @ Y


print("伪逆求得的系数：w1={:.2f}, w2={:.2f}".format(w[0], w[1]))  # 结果接近真实值（噪声影响）

# 验证：用系数预测标签（Y_pred = X @ w）
Y_pred = X @ w
print("\n预测标签：", np.round(Y_pred, 2))
print("真实标签：", np.round(Y, 2))

随机矩阵：
 [[0.17658784 0.84793375]
 [0.79417008 0.50439005]
 [0.2416497  0.88550503]
 [0.32790211 0.42116391]
 [0.02075731 0.10819383]]
真实系数w1: -0.29355463522921255 
真实系数w2: 0.8537496846048703
特征：
 [[0.17658784 0.84793375]
 [0.79417008 0.50439005]
 [0.2416497  0.88550503]
 [0.32790211 0.42116391]
 [0.02075731 0.10819383]]
伪逆求得的系数：w1=-0.29, w2=0.85

预测标签： [0.67 0.2  0.69 0.26 0.09]
真实标签： [0.72 0.14 0.44 0.51 0.99]


In [65]:
# ① QR分解（解方阵系统且追求效率用LU分解，解过定系统、病态矩阵或需要高稳定性用QR分解）
A = np.array([[2,1,-1],[4,-1,1],[-2,3,2]])
Q, R = np.linalg.qr(A)
print("QR分解：Q（正交矩阵）\n", np.round(Q, 2))
print("QR分解：R（上三角矩阵）\n", np.round(R, 2))
print("验证Q@R ≈ A：\n", np.round(Q@R, 2))  # 结果接近A

# ② SVD分解
U, S, VT = np.linalg.svd(A)
# 注意：S是奇异值向量，需转为对角矩阵才能和U、VT相乘
S_mat = np.zeros_like(A, dtype=float)
np.fill_diagonal(S_mat, S)  # 将S填入对角矩阵

print("\nSVD分解：U（左奇异矩阵）\n", np.round(U, 2))
print("SVD分解：S（奇异值向量）\n", np.round(S, 2))
print("SVD分解：VT（右奇异矩阵）\n", np.round(VT, 2))
print("验证U@S_mat@VT ≈ A：\n", np.round(U@S_mat@VT, 2))  # 结果接近A

QR分解：Q（正交矩阵）
 [[-0.41  0.58 -0.71]
 [-0.82  0.12  0.57]
 [ 0.41  0.81  0.42]]
QR分解：R（上三角矩阵）
 [[-4.9   1.63  0.41]
 [ 0.    2.89  1.15]
 [ 0.    0.    2.12]]
验证Q@R ≈ A：
 [[ 2.  1. -1.]
 [ 4. -1.  1.]
 [-2.  3.  2.]]

SVD分解：U（左奇异矩阵）
 [[-0.28  0.33 -0.9 ]
 [-0.72  0.56  0.42]
 [ 0.64  0.76  0.08]]
SVD分解：S（奇异值向量）
 [5.33 3.03 1.86]
SVD分解：VT（右奇异矩阵）
 [[-0.88  0.44  0.16]
 [ 0.45  0.68  0.58]
 [-0.15 -0.58  0.8 ]]
验证U@S_mat@VT ≈ A：
 [[ 2.  1. -1.]
 [ 4. -1.  1.]
 [-2.  3.  2.]]
