In [9]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_eye = np.eye(4) # 对角矩阵，从左上向右下一条线是1，其余为0
arr_zeros = np.zeros((2,3))
arr_rand = np.random.randint(1,10,(2,3))
print(arr,'\n',arr_eye,'\n',arr_zeros,'\n',arr_rand)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
 [[0. 0. 0.]
 [0. 0. 0.]] 
 [[9 8 3]
 [1 7 7]]


In [11]:
A = np.array([[1,2],[3,4]])  # 2x2数组
B = np.array([[5,6],[7,8]])  # 2x2数组

# 1. 元素级乘法（*）：对应位置相乘
print(A * B)

# 2. 矩阵乘法（@ 或 np.dot()）：按矩阵规则计算
print(A @ B)  # 等价于 np.dot(A, B)
# 输出：[[1*5+2*7, 1*6+2*8], 
#        [3*5+4*7, 3*6+4*8]]

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [24]:
'''
即时练习 1：创建矩阵并区分乘法
创建一个 2 行 3 列的矩阵C（元素为 [1,2,3],[4,5,6]）和 3 行 2 列的矩阵D（元素为 [7,8],[9,10],[11,12]）。
尝试计算C * D和C @ D，观察结果差异（思考：为什么C * D会报错？）。
'''
C = np.array([[1,2,3],[4,5,6]])
D = np.array([[7,8],[9,10],[11,12]])
print(C @ D)
D = D.reshape(2,3) # C、D行列数不同不能使用数组乘法
print(C * D)

[[ 58  64]
 [139 154]]
[[ 7 16 27]
 [40 55 72]]


In [29]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A + B)  # 矩阵加法
print(A - 2.5)  # 矩阵减标量

[[ 6  8]
 [10 12]]
[[-1.5 -0.5]
 [ 0.5  1.5]]


In [34]:
'''
即时练习 2：矩阵加减运算
已知E = np.array([[2,4],[6,8]])，F = np.array([[1,3],[5,7]])，计算E - F。
计算E + 3和F * 2（思考：F * 2是矩阵运算还是元素运算？）
'''
E = np.array([[2,4],[6,8]])
F = np.array([[1,3],[5,7]])
print(E - F,"\n",E + 3,"\n",F * 2) #后两者属于元素运算，符合广播机制

[[1 1]
 [1 1]] 
 [[ 5  7]
 [ 9 11]] 
 [[ 2  6]
 [10 14]]


In [36]:
# 1. 矩阵乘法（满足“前列=后行”：A(2x3) * B(3x2) → 结果(2x2)）
A = np.array([[1,2,3],[4,5,6]])  # 2x3
B = np.array([[7,8],[9,10],[11,12]])  # 3x2
print(A @ B)
# 输出：[[1*7+2*9+3*11, 1*8+2*10+3*12], 
#        [4*7+5*9+6*11, 4*8+5*10+6*12]]

# 2. 向量点积（两个1维数组）
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
print(np.dot(vec1, vec2))  # 1*4 + 2*5 + 3*6 = 32

[[ 58  64]
 [139 154]]
32


In [38]:
'''
即时练习 3：矩阵乘法与点积
已知G = np.array([[1,0],[0,1]])（2 阶单位矩阵），H = np.array([[3,4],[5,6]])，计算G @ H和H @ G（观察结果，思考单位矩阵的作用）。
计算向量vec3 = [2,4,6]和vec4 = [3,5,7]的点积
'''
G = np.array([[1,0],[0,1]])
H = np.array([[3,4],[5,6]])
print(np.dot(G,H),"\n",np.dot(H,G)) #任何矩阵与单位矩阵相乘均等于它本身
print(np.dot([2,4,6],[3,5,7]))

[[3 4]
 [5 6]] 
 [[3 4]
 [5 6]]
68


In [48]:
A = np.array([[1,2],[3,4]])  # 2阶方阵
# 1. 转置
print(A.T)

# 2. 行列式（判断是否可逆）
det_A = np.linalg.det(A)
print(int(det_A))  # 结果≠0，可逆

# 3. 逆矩阵
inv_A = np.linalg.inv(A)
print(inv_A)

# 验证逆矩阵：A @ inv_A 应接近单位矩阵（浮点数误差）
print(A @ inv_A)

[[1 3]
 [2 4]]
-2
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [43]:
I = np.array([[2,5],[1,3]])
print(np.linalg.det(I)) #可逆
I_inv = np.linalg.inv(I)
print(I_inv)
print(I @ I_inv)
print(I_inv @ I) #结果一样

1.0
[[ 3. -5.]
 [-1.  2.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [50]:
'''
模块 4：特征值与特征向量（机器学习常用）
对 n 阶方阵 A，若存在标量 λ（特征值）和非零向量 v（特征向量），满足A @ v = λ * v，可通过np.linalg.eig()计算。
'''
A = np.array([[1,2],[3,4]])
eigenvalues,eigenvectors = np.linalg.eig(A)
print("特征值：", eigenvalues)  # 输出两个特征值
print("特征向量（列向量）：\n", eigenvectors)

# 验证：A@v ≈ λ*v（取第一个特征值和特征向量）
v1 = eigenvectors[:,1]  # 第二列是第二个特征向量
lambda1 = eigenvalues[1]
print("A@v1：", A @ v1)
print("λ1*v1：", lambda1 * v1)
# 输出应近似相等（浮点数误差）

特征值： [-0.37228132  5.37228132]
特征向量（列向量）：
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
A@v1： [-2.23472698 -4.88542751]
λ1*v1： [-2.23472698 -4.88542751]


In [59]:
'''
即时练习 5：特征值验证
已知方阵J = np.array([[3,1],[1,3]])，求其特征值和特征向量，并验证J@v = λ*v（任选一个特征值和向量）。
'''
J = np.array([[3,1],[1,3]])
J_λ,J_v = np.linalg.eig(J)
print(J_λ,"\n",J_v)
print(J @ J_v[:,0])
print(J_λ[0] * J_v[:,0])

[4. 2.] 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[2.82842712 2.82842712]
[2.82842712 2.82842712]


In [60]:
A = np.array([[1,2],[3,4],[5,6]])  # 3x2
vec = np.array([10,20])  # 1x2（向量）
print(A + vec)  # 广播：vec扩展为[[10,20],[10,20],[10,20]]

[[11 22]
 [13 24]
 [15 26]]


In [62]:
# 不可逆矩阵（行列式=0）
A = np.array([[1,2],[2,4]])  # 两行成比例，不可逆
pinv_A = np.linalg.pinv(A)
print(pinv_A)
# 验证：A@pinv_A@A ≈ A（伪逆的性质）
print(A @ pinv_A @ A)

[[0.04 0.08]
 [0.08 0.16]]
[[1. 2.]
 [2. 4.]]
[[0.2 0.4]
 [0.4 0.8]]


In [ ]:
from scipy.linalg import lu  # NumPy需借助scipy，或用np.linalg.svd
A = np.array([[2,1,-1],[4,-1,1],[-2,3,2]])
L,U = lu(A,permute_l=True)  # 分解为L（下三角）和U（上三角）
print("下三角矩阵L：\n", L)
print("上三角矩阵U：\n", U)
print("验证L@U：\n", L @ U)  # 应等于原矩阵A